### ISSUE TITLE
Add this list of domains to the list :)

### ISSUE THREAD

**Issue by tahmasebi** [GeroldSetz/emailondeck.com-domains#1]
click2mail.net
amail1.com
urhen.com
nuevomail.com
oppamail.com
edusamail.net
x3mailer.com
mailimail.com
oppamail.com
jalcemail.net
nuevomail.com
p5mail.com
enayu.com
upcmaill.com
mrisemail.com
upcmaill.com
provamail.com
mailvxin.com
jvimail.com
jvimail.com
ismailgul.net
svpmail.com
ismailgul.net
katamo1.com
toracw.com
zaelmo.com
mailcupp.com
reqaxv.com
reqaxv.com
zaelmo.com
reqaxv.com
box4mls.com
jupiterm.com
inbov03.com
box4mls.com
beiop.com
jupiterm.com
lerwfv.com
lywenw.com
lywenw.com
dfb55.com
lywenw.com
dffwer.com
qortu.com
mailnd7.com
lywenw.com
lerwfv.com
lerwfv.com
lywenw.com
dffwer.com
dfb55.com
dfb55.com
btemp.com
oriwijn.com
emltmp.com
dropmail.me
dropmail.me
iopmail.com
mytrumail.com
10mail.org
emlhub.com
finxmail.com
aprimail.com
etoymail.com
supere.ml
yomail.info
laste.ml
smlmail.net
firste.ml
emailnube.com
gilfun.com
hotelnextmail.com
emlpro.com
xmail2.net
x-netmail.com
zeroe.ml
cnetmail.net
chordmi.com
bryanlgx.com
ebamen.gq
cenglandb.com

**Comment by tahmasebi** [comment]
and this list as well :) thanks

xmailsme.com
mailboxt.net
xmailsme.com
era7mail.com
eigoemail.com
qmailers.com
xmailsme.com
mailmink.com
eigoemail.com
era7mail.com
jmail7.com
jmail7.com
xrpmail.com
xmailsme.com
eigoemail.com
qmailers.com
xrpmail.com
jszmail.com
link3mail.com
jszmail.com
webbamail.com
jetsmails.com
jszmail.com
twit-mail.com
adramail.com
link3mail.com
cmailing.com
twit-mail.com
newe-mail.com
tashjw.com
perfumeaffluence.com
misworkbar.gq

**Comment by GeroldSetz** [comment]
Hi,
thanks for your input. The list of domain names in this repo only includes domains used by emailondeck.com. An extensive list (also including all domains you sent) can be found at www.block-disposable-email.com
